apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jwt
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jwt
        track: stable
    spec:
      containers:
        - name: jwt
          image: "veonua/jwt_auth:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 180
            timeoutSeconds: 60
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
          command: ["python3", "/app", "https://<your_domain>", "<your-scope>"]